services:
  config-server:
    image: doriandelaval/config-server
    build: ./config-server
    ports:
      - "9101:9101"
    healthcheck:
      test: "curl --fail --silent  http://localhost:9101/actuator/health | grep 'UP' || exit 1"
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 5 
  eureka-server:
    image: doriandelaval/eureka-server
    build: ./eureka-server
    ports:
      - "8082:8082"
    healthcheck:
      test: "curl --fail --silent  http://localhost:8082/actuator/health | grep 'UP' || exit 1"
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 5
  gateway-service:
    image: doriandelaval/gateway-service
    build: ./gateway-service
    healthcheck:
      test: "curl --fail --silent http://localhost:8081/actuator/health | grep 'UP' || exit 1"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - "8081:8081"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:9101/
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://eureka-server:8082/eureka
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
